---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: gcc
  commands:
  - apt-get update
  - apt-get install -y cmake git libreadline-dev libboost-dev
  - git submodule update --init
  - cmake -DCMAKE_BUILD_TYPE=Release -B build
  - make -C build

- name: publish
  image: plugins/docker
  settings:
    auto-tag: true
    password:
      from_password: dockerhub_pass
    repo: ${DRONE_REPO}
    username:
      from_secret: dockerhub_user

...
